from .common_keyword import get_driver_instance,get_thai_year,get_day_of_week_in_thai
from .common_keyword import get_thai_year,get_day_of_week_in_thai
from .common_keyword import generate_random_number,generate_random_string
from .common_keyword import random_thai_mobile_number,random_thai_citizen_id
from .common_keyword import verify_two_numbers_equal,get_os_platform,get_normalize_path
from .common_keyword import pdf_should_contain,image_should_be_visible_on_screen,wait_until_download_is_completed
from .common_keyword import write_new_row_to_excel_file,column_in_excel_file_should_contains_correct_information,column_in_exported_excel_file_should_exaclty_match
from .common_keyword import get_body_and_link_from_email,get_email_body